/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hangmangame;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.*;

/**
 *
 * @author Tim Reser
 */
public class GameScreen extends javax.swing.JFrame {

    final int POSSIBLE_CHANCES = 6;
    String chosenWord;
    String hiddenWord;
    word_bank1 wordBank;
    String[] image_bank = {"/images/0.jpg",
        "/images/1.jpg",
        "/images/2.jpg",
        "/images/3.jpg",
        "/images/4.jpg",
        "/images/5.jpg",
        "/images/6.jpg",
        "/images/won.jpg",
        "/images/lost.jpg"};
    String[] badGuesses = {"", "", "", "", "", "", ""};
    ImageIcon gallowsIcon;

    /**
     * Creates new form GameScreen
     */
    public GameScreen() {
        initComponents();
        word_bank1 wordBank = new word_bank1();
        chosenWord = wordBank.getWord();
        hiddenWord = "";
        for (int blanks = 0; blanks < chosenWord.length(); blanks++) {
            hiddenWord = (hiddenWord + "_");
        }
        gallowsIcon = new ImageIcon(getClass().getResource(image_bank[0]));
        gallowsPic.setIcon(gallowsIcon);
        tboxLetter.requestFocus();
        updateSecretWord(hiddenWord);
        //makes it so when a user presses Enter, the GUESS button is pressed.
        this.getRootPane().setDefaultButton(bGuess);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gallowsPic = new javax.swing.JLabel();
        bGuess = new javax.swing.JButton();
        bGiveUp = new javax.swing.JButton();
        tboxLetter = new javax.swing.JTextField();
        lSecretWord = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lBadGuesses1 = new javax.swing.JLabel();
        lBadGuesses2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gallowsPic.setBorder(new javax.swing.border.MatteBorder(null));

        bGuess.setText("Guess");
        bGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuessActionPerformed(evt);
            }
        });

        bGiveUp.setText("Give Up");

        lSecretWord.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lSecretWord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lSecretWord.setText("         _ _ _ _ _ _ _ _ _ _ _ _ _ ");

        jLabel1.setText("Incorrect Guesses:");

        lBadGuesses1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lBadGuesses1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lBadGuesses1.setFocusable(false);

        lBadGuesses2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lBadGuesses2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lSecretWord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(49, 49, 49))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(tboxLetter, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bGuess)
                                .addGap(18, 18, 18)
                                .addComponent(bGiveUp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lBadGuesses1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lBadGuesses2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gallowsPic, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(30, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(gallowsPic, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lBadGuesses1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lSecretWord, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bGuess)
                        .addComponent(bGiveUp)
                        .addComponent(tboxLetter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lBadGuesses2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuessActionPerformed
        String nextGuess = tboxLetter.getText().toLowerCase().trim();
        String popUpMessage = "Please only guess one letter at a time.";
        char temp = ' ';
        if (bGuess.getText() == "RESTART") {
            resetGame();
        } else {
            //check to see if the user only entered a letter, then process the guess.
            if (validGuess(nextGuess)) {
                temp = nextGuess.charAt(0);
                processGuess(temp);
                tboxLetter.setText("");
            } else {
                tboxLetter.setText("");
                JOptionPane.showMessageDialog(this, popUpMessage, "Try Again", JOptionPane.ERROR_MESSAGE);
            }
            tboxLetter.requestFocus();
        }
    }//GEN-LAST:event_bGuessActionPerformed
//end bGuessActionPerformed()

    /**
     * This method creates and displays a GameScreen, effectively starting the
     * game.
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameScreen().setVisible(true);
            }
        });
    }

    /**
     * Method checks to see if the user guessed a letter and only one letter.
     *
     * @param in the String to be tested to ensure it's a single letter.
     * @return
     */
    public boolean validGuess(String in) {
        if (!(in.length() == 1)) {
            return false;
        }
        if (!Character.isLetter(in.charAt(0))) {
            return false;
        } else {
            return true;
        }
    }//end validGuess(String)

    /**
     * This method determines if the guess matches one of the letters in the
     * chosen word and then calls the appropriate method to update the
     * GameScreen based on a correct/incorrect guess.
     *
     * @param guess the letter guessed by the user.
     */
    public void processGuess(char guess) {
        boolean goodGuess = false;
        for (int i = 0; i < chosenWord.length(); i++) {
            if (guess == chosenWord.charAt(i)) {
                correctGuess(guess);
                goodGuess = true;
            }
        }
        if (!goodGuess) {
            incorrectGuess(guess);
        }
    }//end processGuess(char)

    private void correctGuess(char letter) {
        String secondHalf;
        boolean blanksRemaining = false;
        for (int i = 0; i < chosenWord.length(); i++) {
            //the hiddenWord index is chosenWord index*2-1
            if (letter == chosenWord.charAt(i)) {
                secondHalf = hiddenWord.substring(i + 1);
                hiddenWord = (hiddenWord.substring(0, i) + letter + secondHalf);
            }
        }
        //check to see if any unguessed letters remain
        for (int j = 0; j < hiddenWord.length(); j++) {
            if (hiddenWord.charAt(j) == '_') {
                blanksRemaining = true;
            }
        }
        updateSecretWord(hiddenWord);
        if (!blanksRemaining) {
            //THEY WON
            gallowsIcon = new ImageIcon(getClass().getResource(image_bank[7]));
            gallowsPic.setIcon(gallowsIcon);
            bGuess.setText("RESTART");
            bGiveUp.setVisible(false);
            tboxLetter.setVisible(false);
        }
    }

    /**
     * This method handles changing the image and incorrect guesses: parts of
     * the GameScreen. If the maximum number of guesses have already been used
     * then the loss image is displayed.
     *
     * @param letter the letter to be added to the incorrect guesses label if
     * there are more guesses available.
     */
    private void incorrectGuess(char letter) {
        int index = POSSIBLE_CHANCES;
        String badLetters1 = "";
        String badLetters2 = "";
        for (int i = 0; i < POSSIBLE_CHANCES; i++) {
            if (badGuesses[i].length() == 0) {
                if (i < index) {
                    index = i;
                }
            }
        }
        //check to see if the user has run out of guesses
        if (index == POSSIBLE_CHANCES) {
            //THEY LOST
            gallowsIcon = new ImageIcon(getClass().getResource(image_bank[8]));
            gallowsPic.setIcon(gallowsIcon);
            bGuess.setText("RESTART");
            bGiveUp.setVisible(false);
            tboxLetter.setVisible(false);
        } //the user still has guesses left
        else {
            //add the bad guess to the badGuesses array
            badGuesses[index] = ("" + letter);
            for (int j = 0; j < 3; j++) {
                badLetters1 = (badLetters1 + badGuesses[j] + " ");
            }
            for (int k = 3; k < 6; k++) {
                badLetters2 = (badLetters2 + badGuesses[k] + " ");
            }
            //update the GameScreen
            lBadGuesses1.setText(badLetters1.toUpperCase());
            lBadGuesses2.setText(badLetters2.toUpperCase());
            gallowsIcon = new ImageIcon(getClass().getResource(image_bank[index + 1]));
            gallowsPic.setIcon(gallowsIcon);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bGiveUp;
    private javax.swing.JButton bGuess;
    private javax.swing.JLabel gallowsPic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lBadGuesses1;
    private javax.swing.JLabel lBadGuesses2;
    private javax.swing.JLabel lSecretWord;
    private javax.swing.JTextField tboxLetter;
    // End of variables declaration//GEN-END:variables

    private void updateSecretWord(String hiddenWord) {
        String output = "";
        for (int i = 0; i < hiddenWord.length(); i++) {
            output = (output + hiddenWord.charAt(i) + " ");
        }
        lSecretWord.setText(output);
    }

    private void resetGame() {
        for (int i = 0; i < badGuesses.length; i++) {
            badGuesses[i] = "";
            System.out.println("badGuesses: " + badGuesses.toString());
        }
        bGuess.setText("Guess");
        bGiveUp.setVisible(true);
        tboxLetter.setVisible(true);
        word_bank1 wordBank = new word_bank1();
        chosenWord = wordBank.getWord();
        hiddenWord = "";
        for (int blanks = 0; blanks < chosenWord.length(); blanks++) {
            hiddenWord = (hiddenWord + "_");
        }
        gallowsIcon = new ImageIcon(getClass().getResource(image_bank[0]));
        gallowsPic.setIcon(gallowsIcon);
        tboxLetter.requestFocus();
        updateSecretWord(hiddenWord);
        lBadGuesses1.setText("");
        lBadGuesses2.setText("");
    }

}
